### ISSUE TITLE
Take everything and leave option

### ISSUE THREAD

**Issue by Dostoi** [doublespeakgames/adarkroom#200]
Instead of clicking several time on every items and then clicking on leave, it would be easier to be able to just click on an option like take everything and leave
And even being able to take a stack of item instead of just one

**Comment by Anish-Agnihotri** [comment]
I'll for the repository and try that out! Good Idea!

**Comment by grotewold** [comment]
I believe 7208b845b1e5a58ce80bf9c7f84a91ae0ef58da4 resolves this, Thanks!
