### ISSUE TITLE
Changing language reset UI

### ISSUE THREAD

**Issue by Guybrush21** [doublespeakgames/adarkroom#330]
If you click on an item from the language selector (even if you don't actually change the language) the dark-light mode resets to light, the notification panel resets itself also the hyper mode resets to classic.

This behavior could be consistent in the notification area, preventing different languages appearing at the same time, but for the hyper and light mode I find it a bit annoying. 

Shouldn't this configuration be local stored like the language is? 
As I can see the only problem is that when you change language a page refresh is done and this elements aren't cached.

I'm trying to solve this, if you are interested, using localStorage or some other suggestion if you have any.

Please, forgive me if I'm doing this in a wrong way, adarkroom is my first github issue and actually open source experience.

**Comment by skj3gg** [comment]
Welcome!

These ideas are great and would all help make the experience feel seamless. As a first step, it would be great if you add hyper mode and lights off into the game's `State`. Thanks!

**Comment by Continuities** [comment]
Hey Nicholas!

Agree completely, though it'll be some work to keep the notification pane in sync. Language changes trigger full page refreshes, which is why everything resets. Keeping hyper mode and lights-out in the State, like @skj3gg mentioned, is pretty simple but keeping the notifications in sync will require keeping all of it in the State as well, then syncing it up when the page loads.

**Comment by nicholaspellizer** [comment]
I've finished writing the code which manages the hyper and lightsOff modes here: 
https://github.com/nicholaspellizer/adarkroom/commit/541c7ea95ec71810b9f73404080c53bc0d2fb22f

It's not really much more more than a 
```javascript
$SM.set('config.lightsOff', Engine.isLightsOff(), false);
```
after lights switching and
```javascript
if($SM.get('config.lightsOff')){
    Engine.turnLightsOff();
}
```
in the init.
But I'm having some issue getting things done in chrome and IE, while Firefox is good. It's like the $SM.set() method randomly fails only in chrome and IE. 
Any suggestion?

**Comment by Continuities** [comment]
Took a look at your branch, and you've got a syntax error in state_manager.js. Could be your problem. I commented on the commit.

**Comment by tomisy** [comment]
The timers also reset when you change the language.

**Comment by nicholaspellizer** [comment]
AFAIK the timer behaviour is intentional. I'd read something about it recently here, but I can also be wrong.
Anyway, shame on me for the syntax error, but it not seem influent for the issue, i'm still working on it. Thank you for the help.

**Comment by grotewold** [comment]
This seems solved, If I'm wrong let me know!

Thanks!!
