### ISSUE TITLE
Increase arrows: +10 is in 'ones' place and +1 is in 'tens' place

### ISSUE THREAD

**Issue by underscorejho** [doublespeakgames/adarkroom#333]
I find this counter intuitive. I assumed the arrow in the 'tens' place would increment +10 when I played.

**Comment by skj3gg** [comment]
I'm not sure if this wouldn't be too confusing this far into the games life to change now. Maybe if there were column headers at the top like `10s` and `1s` I could see the change being made.

**Comment by underscorejho** [comment]
Understandable. I think that besides switching them, there's not much to do that won't clutter the page. I'd be alright with leaving it.
