### ISSUE TITLE
Cooldown buttons and cheating

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#351]
Some players have probably noticed it. There's a way to easly stack great quantities of wood and traps content, and it also allows explorers to avoid waiting for embark after having dead. All they have to do is reload the game. Achievements remain and the buttons are ready to be clicked again.
What if buttons on load started with full cooldown time? This'd mean that if a player reloads, he has to wait for the **entire** time again (possibly in addition to what s/he has already waited for :facepunch:)
Is it too bad?

**Comment by Continuities** [comment]
I do think this is a little heavy-handed. If we hit players with a full cooldown on load, then genuine return visitors (or first-time visitors, for that matter) won't have something to do the instant they hit the page. Those first few seconds of interaction are key.

If we *were* to implement something like this, we'd have to be a bit more sophisticated about detecting actual reload-abuse. Perhaps by storing a "departure time" onpageunload and comparing it against the current time onpagelod.

I've known about this issue forever, though, and I honestly don't think it's a problem. If people want to cheat, there's a lot more they can do than just resetting the timers. I'm not in the business of forcing people to play in one particular way, I just set up the systems for them to play within.

**Comment by AndySky21** [comment]
I thought about returning visitors indeed, and I didn't know how to put the 2 things together.
I must admit that when I read the answer about "idle games" I thought you'd have agreed on this one (I mean, reloading actually breaks with the "idleness" thing).
Yes, a way would be to store in the save the actual advancement for cooldown buttons (not the fire, of course. Just wood gathering, traps checking and embarking) so that, on load, the buttons continue cooling down from the saved point.
But I guess this is entirely unnecessary.

**Comment by Continuities** [comment]
I'm not *against* an anti-cheating measure. I just don't really care enough to do it myself =)

Storing the cooldown timers for each button would totally work.

**Comment by AndySky21** [comment]
Haha! =) 
contributor says the save could store timer values, given the means.
says he'll make up something later.

**Comment by AndySky21** [comment]
Almost done. I only have to understand why traps are not initialised until player clicks on Outside tab, because this means that stored cooldown only starts at that point (embark and gather wood always start on load instead).

**Comment by grotewold** [comment]
Woot! Closing thanks to @AndySky21's great work
