### ISSUE TITLE
Someone will stoke the fire for me.

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#352]
The game suggests the player to regularly stoke the fire, as it progressively dies and the room's temperature lowers. This also means that some wood should always be there. But:

1. The builder gathers 2 wood units every 10s
2. The builder automatically stokes the fire when it's dying.

While I *do* appreciate the builder's efforts to gather wood (which is necessary pretty much for everything, even more now that huts can burn), I find it **too easy** for the player that she stokes the fire too.
What if she *didn't* do it, so that if the player does not care the fire extinguishes and activities stop? This would force players to keep the room under control even in advanced phases of the game, when most attention is paid to the Dusty Path.
(Note: the builder could still stoke the fire while exploring the map, maybe).

**Comment by Continuities** [comment]
This interaction is *entirely* intentional.

Due to the nature of idle games, it's expected that players will spend large amounts of time not interacting with the game. I want there to always be something to do whenever they return to the tab, especially after a long absence. If they player leaves the game to generate enough materials to build something they're excited for, I want them to be able to build that thing immediately, not blocked from taking action because they didn't come back often enough. Taking out the builder's ability to stoke the fire actively punishes people for playing ADR the way it suggests that it should be played.

**Comment by AndySky21** [comment]
Yeah, I didn't consider that.

**Comment by AndySky21** [comment]
Sorry if I write this here, but I prefer not bothering developers with a new issue, as it's a related matter.
In "room.js" at line ~910 the builder "just shivers" when trying to build something if room is cold. Does it really happen? The builder stokes the fire so the room is never colder than "mild" and she gathers fire so it doesn't run out.
(note: In my personal version I changed the parameter into "mild", so that the builder keeps stoking the fire but I have to do by myself in order to make the room "warm", if I want buildings.)

**Comment by skj3gg** [comment]
This used to happen before the fire was placed in State. As it stand, it is probably unreachable code at this point, but would need to double check.

**Comment by AndySky21** [comment]
I only have to test what happens if on load (so counters are reset) net wood gathering is 0 and starting value is 0 too. Let's say, 3 charcutiers (-15 wood/tick) and 13 gatherers (+13 wood/tick) plus the builder (+2 wood/tick). If the script does not give the builder any priority, then she hasn't "the time" to stoke the fire and the room can become cold.

**Comment by AndySky21** [comment]
I cannot succeed in keeping wood = 0 as it replenishes some seconds before it's used. So the game has some seconds to allow builder stoking the fire.
I'm not sure whether the room can still turn cold, but that part of code can still be a starting point for improvements, so I don't think it will be removed.....

**Comment by daveschaefer** [comment]
@Continuities This is a great bit of game design info here too. Do you think it would be worth adding a summary of your design intent as a comment in the code? And/or what do you think about a 'game design' label on GitHub to easily collect all of the discussions and knowledge that aren't in the Design Guide?

**Comment by Continuities** [comment]
@daveschaefer I'm always in favour of more/better documentation. I just don't like writing it =)
