### ISSUE TITLE
The compass always points once

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#353]
When buying a compass, it points "somewhere" (I must re-check, but I guess it points towards the ship, doesn't it?), but that information is given only once. Is it intentional or should this direction be repeated somehow? (e.g. when reloading the game)

**Comment by Continuities** [comment]
The compass does point toward the ship. It was intentionally only displayed once, but I'm open to the possibility of repeating the message if it fits. Convince me =)

**Comment by AndySky21** [comment]
In my opinion, that particular adds something to the mystery. When the player reads it, it's almost as if "something" is telling him/her that, while every direction is good in the map, THAT direction means something important for the story.
But the game moves on, and if the player doesn't quickly move towards that direction, s/he will probably forget it. E.g. if the compass points south but I see something "strange" towards north, I could go there, then move forward and leave South for last, exploring it "casually". The same if I cannot embark soon after having bought the compass, because I want to equip better.
Also count that the specificity of "the compass points..." could be lost if a player considers it a completely random notice (also because it does not appear again, the first time I saw it I thought it was something funny like notifications regarding buildings. I needed to play 3 times to understand that the compass always points towards something specific). But if the same notice is repeated sometimes, well, it becomes an intriguing warning. Why the h*ll does this thing always point there? There's something interesting, maybe...

**Comment by skj3gg** [comment]
What if the "the compass points..." showed up in a popup box instead of just to notification panel?

**Comment by AndySky21** [comment]
It would surely point out that it's not a random fact. In ADR everything showing up in panels is meaningful.

The only remaining issue is that the player must write it down somewhere in order to remember it. It could appear as a tooltip on the compass, maybe, if the player deserves being helped somehow.

**Comment by Continuities** [comment]
I'm sold on the idea of repeating it, but we have to be careful not to push
it too hard. If it seems really important, it could be assumed that it is
the next immediate goal, which would lead players to push recklessly in one
direction without first gaining the equipment required to get there.

I actually think adding a tooltip to the compass in the stores panel is a
pretty good solution. The information is there if you look for it, but it's
not pushed right in the player's face.

Make it so.

**Comment by AndySky21** [comment]
Roger, Commander.

**Comment by daveschaefer** [comment]
I'd just like to say thanks @AndySky21 for bringing this up. I've played a *lot* of ADR and I never made the connection between the direction the compass points and the direction of the ship. Very cool bit of game design to uncover :)

+1 vote for adding it as a tooltip in the stores panel so it's not glaringly obvious but you can still reference it later. Nice improvement.

**Comment by nicholaspellizer** [comment]
+1 for the tool tip on the compass item. 
On my first attempt when the game told me the compass was pointing north I registered it as an important information, but when I restarted the compass was pointing again north so I assumed it wasn't a random thing.

**Comment by AndySky21** [comment]
Quick note on job advancing: as World works now, the ship's position is registered on setting, not on getting.
I'd like to create a new method for World, for mapping the position of things on the map. Would it be useful for further development? Or should I just fix the ship position in a property?

**Comment by Continuities** [comment]
For what purpose? The way it's currently implemented provides all the info you need, no?

**Comment by AndySky21** [comment]
I'm reviewing it because I probably missed something.
But for what I see World.dir is only available when the map is generated, so it can provide the direction for the initial notification. But when the game is reloaded and the map itself is not generated, World.dir does not exist.

**Comment by Continuities** [comment]
Oh yeah, you're right. Since I'm lazy, I'd probably just persist World.dir
in the state, and regenerate it by crawling the map if it's missing (for
backwards compatibility).

**Comment by AndySky21** [comment]
I thought about it tonight, but it seems too much for State to store both the map **and** the direction.
I'd move the dir builder to a new property and fix it up a little bit.
I heard you like exploring, so my method will map your map so you can explore what you'll explore.

**Comment by skj3gg** [comment]
![](http://cdn.meme.am/instances/500x/61922730.jpg)

**Comment by Continuities** [comment]
I don't wanna jump to any conclusions, but I think this might be the best open source project on the internet. Thanks everyone =)

**Comment by AndySky21** [comment]
I discovered it thanks to ChromeExperiments. I loved it since then, and even if I discovered other text/ascii art adventures online, ADR remains something great for its atmosphere and richness of aspects and amazing features. Thank you for having lighted the fire, we only stoke it!
