### ISSUE TITLE
Missing notifications

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#363]
Kill me. ASAP.
A lot of events miss a notification. Packs of beasts, military raids, diseases and plagues leave no trace in the game history.
On the contrary, the hut fire has 2 notifications (don't remove the second one, I have an issue for that too. I told it. Kill me.)

**Comment by Continuities** [comment]
Really? That's bad. Used to work before I let all you folks mess around in
the code! =)

**Comment by AndySky21** [comment]
Really?
As soon as I discover who removed the "notification" property from so many event scenes, s/he will end up like the thief. =P
(I mean that I'll ask him/her how to be stealthy!)

**Comment by AndySky21** [comment]
After a quick review, I see that notification strings do not appear in pot file. Please, when you have the time, fix it by adding them in tone with the text. I love playing with the code, but I'd never lay a finger on the artistic part. :)

**Comment by grotewold** [comment]
> but I'd never lay a finger on the artistic part

I think you did great!
