### ISSUE TITLE
Unfair blood-greedy fire

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#364]
Hut fire invariably kills 4 innocent people.Even if I have 20 huts and I only have 6 villagers. It never destroys an empty or partially full hut.
And, in addition to this, if the fire destroys a hut when I only have empty huts (it may happen), the windows always says that there are villagers to mourn (the first time I thought it had killed the builder - I'm serious).
Possible improvement: 
Let's assume that villagers always fill in all possible huts, even if they're strangers (it's a barren world, after all, and they cannot be too choosy). Let's number huts from 1, so that they are progressively filled in (first 4 villagers occupy hut 1, then the fifth goes to 2 etc). This means that, if at time T there are 4 huts and 10 villagers, huts 1 and 2 are full, hut 3 has 2 inhabitants and hut 4 is empty.
When a fire rampages, a random number is generated between 1 and (huts), in this case between 1 and 4. The corresponding hut is destroyed, and if it's inhabited the villagers inside die. If this number is positive, the dialog says to "mourn" dead people, otherwise it could just say "remove the wreckage".
Consider that a hut fire is always a damage, especially if it comes when a player is trying to reconstruct a village after a series of previous similar events. If it also invariably kills so many, it's disastrous.

**Comment by defiler** [comment]
I think fire starts because of villager activity inside a hut (careless villagers), so fires should not start in uninhabited huts?

**Comment by AndySky21** [comment]
Yes, you are right and I thought it by myself while working on it.
In my commit, Hut fire can only destroy populated huts. But it can sometimes destroy the least populated one (assuming that population tends to occupy the lowest possible number of huts).
