### ISSUE TITLE
Unexplicit Hyper Mode Exceptions

### ISSUE THREAD

**Issue by lancehalberd** [doublespeakgames/adarkroom#374]
It seems hyper mode is intended to double the speed of the game, but does not effect the following timers:
Income generation (uses window.setTimeout instead of Engine.setTimeout)
Button cool downs (uses animation duration instead of Engine.setTimeout)

I think the first is probably just a mistake, but if not, consider using Engine.setTimeout and passing the skipDouble flag as true to make it clear that this is the desired behavior.

I'm not sure about the cool downs, but my experience was that since hyper mode didn't seem to effect these, I wasn't quite sure if hyper mode even worked other than to make combat more difficult.

**Comment by Continuities** [comment]
Huh. I'd say it should affect those things.

**Comment by skj3gg** [comment]
Thanks you for finding this!

**Comment by lancehalberd** [comment]
Wow, prompt response, thanks everyone! Great game btw.
