### ISSUE TITLE
Missing builder tooltip outside

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#382]
This is funny.
When there are no gatherers and the only source of wood is the Builder, it is pointed out with the tooltip. In room.
While outside, tooltip disappears. It only exists if there are gatherers.

**Comment by AndySky21** [comment]
Update: it's a CSS issue. The tooltip *exists*, but it is not shown until there also appears the "village" box.

**Comment by skj3gg** [comment]
This was fixed with #383
