### ISSUE TITLE
can't seem to select occupations

### ISSUE THREAD

**Issue by jacob-keller** [doublespeakgames/adarkroom#387]
When in the village tab, I can't seem to select the occupation despite seeing buttons near each one. It seems like I've unlocked them but now I can't make use of them which has prevented any sort of progression.

Is there something I am doing wrong?

**Comment by jacob-keller** [comment]
Never mind, I realized the buttons were incredibly small. Maybe something could be done to make them more visible in the "lights out" display?

They are much more difficult to understand in lights out mode.

**Comment by skj3gg** [comment]
move you save to https://doublespeakgames.github.io/adarkroom/ and let me know if those arrows are more helpful. An update to those buttons was recently added but hasn't been pushed to production yet.
