### ISSUE TITLE
Carrying a Ship

### ISSUE THREAD

**Issue by AndySky21** [doublespeakgames/adarkroom#400]
There's something I don't understand. When you find and salvage the ship, how are you supposed to bring it back home? At first I thought it was carried (I had the convoy after all), then I realized that no free space is used while carrying it, and it has 1 of engine reinforcement when the Ship panel is created, so I guess it's the ship which brings back the expedition. Then, 2 questions:

1. shouldn't it grant the player some benefit when retrieved? like, IDK, moving faster or carrying more stuff
2. shouldn't it need some cost for salvaging? Like, IDK, having to spend some Iron/Steel/Alien Alloy you carry, or you have to wait until you can.

The 2 things are completely unrelated, of course. I only ask it because ADR is built around consistency, to the point that the map is forced to put forest around the village to honor the fact that you "gather wood from a forest" (I see what you've done there).

**Comment by Continuities** [comment]
Like the mines, the idea is that a permanent route has been established
between the village and the ship. Nothing is carried.

**Comment by AndySky21** [comment]
Now I feel stupid.

**Comment by Continuities** [comment]
=)
