### ISSUE TITLE
Keyboard input can change tabs when there's an overlay

### ISSUE THREAD

**Issue by wmassingham** [doublespeakgames/adarkroom#403]
Specifically reproducible in the save/load overlay dialog, possibly others (e.g. events?).

1. Click `save.`
2. Press left/right
3. Observe the game changing tabs underneath

Solution: use the same tab-disable code used when returning from the world?

**Comment by wmassingham** [comment]
Confirmed to also happen with events.

**Comment by AndySky21** [comment]
Done with tab navigation. Will you do the same with the Panel creation function? it's quite easy! I never saw that bug, but it's just because I don't like navigating with arrows.

**Comment by wmassingham** [comment]
I set `Engine.tabNavigation` as necessary in `startEvent()` and `endEvent()`, and that seems to have fixed it. Can you explain what you mean about the panel creation function?

**Comment by AndySky21** [comment]
I meant startEvent.
Well done. I will cherrypick your changes into my personal version before they're merged :D
