### ISSUE TITLE
Increase/Decrease buttons hard to click/unclear what they do 

### ISSUE THREAD

**Issue by monbicon** [doublespeakgames/adarkroom#410]
![screen shot 2015-06-11 at 3 00 14 pm](https://cloud.githubusercontent.com/assets/5492810/8100224/4610feda-104c-11e5-8688-e2e659aed15e.png)
I find these buttons hard to click. At first I didn't think they were buttons as I'd tried to click them a few times with no results. Now I know they are and I still find them frustrating to use. 

Wouldn't a + - be clearer and easier to click? Maybe long-click to fill/empty?

Edit: Playing on my Desktop PC later with a mouse, it was fine. Before the cursor wasn't always detecting the link, it was not changing into the hand-cursor, staying the pointer-cursor. I could click behind the arrows and nothing would happen.

**Comment by monbicon** [comment]
I can't recreate the issue. And I've been playing for hours.

**Comment by wmassingham** [comment]
No, I agree with you. The issue is that the "down" button overlaps the "up" button. When the down button is disabled, it means that half the up button is obscured and is unclickable.

**Comment by monbicon** [comment]
You're correct wmassingham! I just tried it then and that is what's causing the issue.

**Comment by AndySky21** [comment]
If button overlapping is the only issue, I tried to fix it with #411.

**Comment by grotewold** [comment]
I believe #411 resolved this issue. Thanks!
