### ISSUE TITLE
Change Font, Add Color

### ISSUE THREAD

**Issue by brendonho01** [doublespeakgames/adarkroom#418]
The Serif Font looks unappealing.
Replace with google font:

Put into index.html:
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

put into style.css:
font-family: 'Roboto', sans-serif;

Hope you add these

Also add appealing coloe

**Comment by grotewold** [comment]
While I agree a serif font like "Times New Roman" is not the prettiest, it IS the iconic font of the game for 2+ years now. I'll leave it to @Continuities to decide. Additionally, importing a gfont may be overkill.

Colors are a no until #210 is resolved

**Comment by emanb29** [comment]
No no no. While I detest serif fonts, it's such a part of this game, I wouldn't want to change it. Though an option might be a good idea.

**Comment by Continuities** [comment]
I'm not opposed to a theme picker (expanding on the "lights off" option),
so long as the original style stays default.

**Comment by grotewold** [comment]
Consolidating this issue into #210. Hopefully it will get accomplished soon so that your own theme can be made.
