### ISSUE TITLE
Javascript errors in Safari?

### ISSUE THREAD

**Issue by Muffo** [doublespeakgames/adarkroom#424]
When I open the webpage from Safari it does not show anything.
I checked the Javascript console and I have seen the following errors:

    [Error] SyntaxError: Unexpected token '('. Expected a ':' following the property name 'removeBranch'.
        (funzione anonima) (state_manager.js, line 197)
    [Error] ReferenceError: Can't find variable: $SM
        loadGame (engine.js, line 261)
        init (engine.js, line 104)
        (funzione anonima) (engine.js, line 806)
        c (jquery.min.js, line 4)
        fireWith (jquery.min.js, line 4)
        ready (jquery.min.js, line 4)
        q (jquery.min.js, line 4)

This seems to work fine on Chrome

**Comment by grotewold** [comment]
Thanks! This has been fixed in 95cf44c2f21f4feb99683cf819b209bc887e19cb and will be put into the production server soon

cc @Continuities
