### ISSUE TITLE
Moving content out of other files

### ISSUE THREAD

**Issue by LucidCrux** [doublespeakgames/adarkroom#43]
I'm new to gitHub and javascript, but I'd like to take a shot a moving content away from the mechanics. The main reason is that coming from other languages, having content mixed in with everything else bugs the crap out of me. The second reason is that it will hopefully make things a lot less messy, meaning easier to add new stuff and easier to find the mechanics you want without all the clutter.

I did not want to make a pull request or start a branch yet because 1) I'm new to github and this kind of project management 2) I have no clue how long this will take me to do

In lieu of forums, I'm starting this issue for discussion on the idea and feedback on what I've got going. If doing that is inappropriate, feel free to squash this.

Below are two files I'm working on. If you have suggestions or see problems let me know. I have not tested any of it (I know very bad me). Some of it may also look new because I am trying to think ahead to possible future content.

content.js

```JavaScript
/**
 * Module for Content
 */

var Content = {
	buildingList: {},
	upgradeList: {},
	itemList: {},
	weaponList: {},
	mobList: {},
	
	//checks if object of the given name is already in the list
	//if not, adds object to the list, else alerts name exists
	addContentListEntry: function (newContent, whichList) {
		if(!(newContent.name in whichList)) {
			whichList[newContent.name] = newContent;
		} else {
			alert("The list already has an entry for \"" + newContent.name + "\".")
		}
		
	},
	
	//reads each entry from a stat list
	//then creates the correct object type and copies those stats
	//then makes a call to add the object to the given content list
	// *Does not include any kind of error or type checking
	populateListFromStats: function (statList, objType, contentList) {
		for(var entry in statList){
			var tempObj = Object.create(objType);
			jQuery.extend(tempObj, entry);
			Content.addContentListEntry(tempObj, contentList);
		};
	}
};

/**
 * The following are the objects used for OO / "class"
 * type functionality for use with Javascript
 * prototyping inheritance.
 */

Content.Thing = [
	name: 'new thing',
	button: null,
	type: 'thing',
	availableMsg: null,
	buildMsg: 'made a thing',
	cost: {},
	getCost: function (index) {
		if(index == undefined) {
			index = 0;
		};
		return this.cost[index];
	}
];

Content.Building = Object.create(Content.Thing);
jQuery.extend(Content.Building, {
	type: 'building',
	availableMsg: 'new building available',
	maximum: 1
});

Content.Upgrade = Object.create(Content.Thing);
jQuery.extend(Content.Upgrade, {
	type: 'upgrade',
	maximum: 1
});

Content.Item = Object.create(Content.Thing);
jQuery.extend(Content.Item, {
	type: 'item',
	drops: {},
});

Content.Equipment = Object.create(Content.Thing);
jQuery.extend(Content.Weapon, {
	type: 'equipment',
	equipType: 'misc',
	
});

Content.Weapon = Object.create(Content.Equipment);
jQuery.extend(Content.Weapon, {
	equipType: 'weapon',
	weaponType: 'melee',
	damage: 1,
	cooldown: 1,
	verb: 'hit',
	useCost: {}
});

Content.Mob = [
	name: 'mob',
	char: 'm',
	notification: 'a mob appears',
	damage: 1,
	hit: 0.5,
	attackDelay: 1,
	health: 10,
	terrain: World.TILE.FIELD,
	loot: {},
];
```

content_lists.js

```JavaScript
//Arrays of content info grouped in one place

//Buildings
Content.buildingStatArray = [
                         
];

//Upgrades
Content.upgradeStatArray = [
                         
];

//Items
Content.itemStatArray = [
                         
];

//Weapons
Content.weaponStatArray = [
	//Unarmed
	{
		name: 'fists',
		weaponType: 'unarmed',
		damage: 1,
		cooldown: 2,
		verb: 'punch'
	},
	//Melee
	{
		name: 'bone spear',
		weaponType: 'melee',
		damage: 2,
		cooldown: 2,
		verb: 'stab',
	},
	{
		name: 'iron sword',
		weaponType: 'melee',
		damage: 4,
		cooldown: 2,
		verb: 'swing'
	},
	{
		name: 'steel sword',
		weaponType: 'melee',
		damage: 6,
		cooldown: 2,
		verb: 'slash'
	},
	{
		name: 'bayonet',
		weaponType: 'melee',
		damage: 8,
		cooldown: 2,
		verb: 'thrust'
	},
	//Ranged
	{
		name: 'rifle',
		weaponType: 'ranged',
		damage: 5,
		cooldown: 1,
		verb: 'shoot',
		cost: { 'bullets': 1 }
	},
	{
		name: 'laser rifle',
		type: 'ranged',
		damage: 8,
		cooldown: 1,
		verb: 'blast',
		cost: { 'energy cell': 1 }
	},
	{
		name: 'grenade',
		type: 'ranged',
		damage: 15,
		cooldown: 5,
		verb: 'lob',
		cost: { 'grenade': 1 }
	},
	{
		name: 'bola',
		type: 'ranged',
		damage: 'stun',
		cooldown: 15,
		verb: 'tangle',
		cost: { 'bola': 1 }
	}
];

//Mobs
Content.mobStatArray = [
	//============ tier 1 ============//
	{	name: 'snarling beast',
		char: 'B',
		notification: 'a snarling beast leaps out of the underbrush',
		damage: 1,
		hit: 0.8,
		attackDelay: 1,
		health: 5,
		terrain: World.TILE.FOREST,
		loot: {
			'fur': {min: 1, max: 3, chance: 1},
			'meat': {min: 1, max: 3, chance: 1},
			'teeth': {min:1, max: 3, chance: 0.8}
		}
	},              
];

//Populate the content lists with actual objects created from these stats
Content.populateListFromStats (Content.buildingStatArray, Content.Building, Content.buildingList);
Content.populateListFromStats (Content.upgradeStatArray, Content.Upgrade, Content.upgradeList);
Content.populateListFromStats (Content.itemStatArray, Content.Item, Content.itemList);
Content.populateListFromStats (Content.weaponStatArray, Content.Weapon, Content.weaponList);
Content.populateListFromStats (Content.mobStatArray, Content.Mob, Content.mobList);
```

**Comment by anubisthejackle** [comment]
This would be do-able using something like Angular.

**Comment by anubisthejackle** [comment]
I've actually been thinking about this for a while. A large part of the learning curve for me when I started working on the codebase was the strong connection between the logic and the template. I think if that was separated, even if it wasn't done using Angular, it would help things, but as mentioned it's a huge project.

**Comment by Continuities** [comment]
Yeah, separation of concerns would do the project serious good. I don't think we need to introduce a new framework to do it, but something like what @LucidCrux proposed would go a long way to cleaning things up.

**Comment by trcollinson** [comment]
So out of curiosity is there a reason not to use a framework, even a small one, like backbone or react? I know it would be a major refactoring but the effort would be worthwhile moving along. 

Additionally, has any thought been put into eventually adding any sort of multiple player and server side functionality?

**Comment by Continuities** [comment]
The main reason is because I'm not a fan of frameworks. I find them too restrictive; often having to resort to weird hacks to do things that the framework didn't anticipate. Were I writing ADR again, I probably wouldn't even use jQuery. Building something from scratch is, for me, a big part of the fun of software development.

That said, I did a crappy job of architecting ADR so maybe I don't deserve the freedom...

I haven't personally thought about server-side functionality, but I'm not opposed to it. Assuming, that is, that someone wants to help me pay for beefier servers to support it. =)

**Comment by anubisthejackle** [comment]
I've been toying with semi-server side functionality with github pages. Haven't come up with any definitive solutions yet, but I think being able to tie into a GitHub repo VIA API to store saves would be a unique solution.

As for frameworks, the main issue people have with frameworks that I've seen is bloat. Unless you're using the majority of the framework repeatedly, you're probably including features that you really don't need.

**Comment by trcollinson** [comment]
@Continuities I totally understand the sentiment! I mean I have created web servers from scratch in c just for the heck of it. And often I have regretted doing things like that because eventually they get to someone else and I think, oh boy I shouldn't have done it like I did. No worries! Projects like this are supposed to be fun right?

@anubisthejackle I am with you there, frameworks can add quite a bit of bloat. But they can also make the architecture easier to understand and maintain in the long run.

I guess the real question in all of this is where is ADR going? And I don't mean that in a snarky way at all. More in the sense of, would there be a lot of benefit in changing up and refactoring the architecture. Would it move the needle forward on newer features and functionality?

**Comment by Continuities** [comment]
> I guess the real question in all of this is where is ADR going?

Here's where I step back and let the community at large decide. Since I'm basically not working on ADR any more (I tire of things quickly, and am constantly shifting to new projects), I have no personal stake in the architecture of the code. If the general consensus is that moving to a framework would be easier in the long run and provoke more new content, then I'm all for it.

**Comment by grotewold** [comment]
I will add my two cents to this, which is, while this would be great and *maybe* fix some issues. It just seems out of the project scope this late in the game. If someone really tried to tackle all of this, I have a fear that the blast radius of the changes would be too great to feel comfortable with them.

I'll let this sink in, allow some comments, and if nothing compelling, I'm going to close this. This little issues been open for too long.

**Comment by anubisthejackle** [comment]
I tend to agree. It's a huge change, which has some benefit. The same
benefit could be achieved by simply improving documentation in a wiki,
though. I'd say that's probably the better route.
