### ISSUE TITLE
Improve Spanish translation

### ISSUE THREAD

**Issue by ngosang** [doublespeakgames/adarkroom#430]
There are several strings untranslated in Spanish language but the strings are not in the .po file. How I can update the .po file to include all strings?

**Comment by Continuities** [comment]
I'm not exactly sure about the translation process, but perhaps rerunning the steps to create the .po file (documented in docs/translation.txt) would do the trick?

> 3) Create the new po file:
> 
>   ubuntu:
>	msginit --locale {locale for new language eg: en_US} -i lang/adarkroom.pot -o lang/{new_language}/strings.po
>   windows:
>         - open application interface > File > New... > [select language for translation] > Save as... > lang/{new_language_code}/strings.po
>        - [update from POT file] > select lang/adarkroom.pot

**Comment by ngosang** [comment]
I know how.
