### ISSUE TITLE
Instructions for updating template file aren't working

### ISSUE THREAD

**Issue by bdorer** [doublespeakgames/adarkroom#440]
For Windows & Mac Translators can use Poedit for creating and updating translations.

To do this easily the file adarkroom.pot should be updated when messages are changed or added. This would make translating a lot easier.

I tried to update the file according to the instructions in doc\translations.txt but couldn't find the requested menue entry.

**Comment by gitupofftheflooranddosomework** [comment]
please close no longer relevant
