### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by olegboleg** [doublespeakgames/adarkroom#452]
I "saved" (exported) the game while exploring the map. I had to import the game later from that export. everything is fine, except that my screen wasnt showing the map but the main screen, and i cannot embark anymore (greyed out, but no timer). Also my whole Equipment of the expedition is gone.

seem to me like i should just see the map to bring ym expedition home.

**Comment by olegboleg** [comment]
my bad, i can embark again. 

still think my euqipement is lost

**Comment by AndySky21** [comment]
As far as I know, there is no state save during map exploration. Thus if you save and reload it's just as if you had died while exploring. This is why embark button cools down and equipment is lost.

**Comment by olegboleg** [comment]
it actually didint cool down. it was just grey becuase the euqiment was gone (= no meat no embark)

**Comment by olegboleg** [comment]
yes the equiement was lost. :(
