### ISSUE TITLE
#spacePanel overlaps menus

### ISSUE THREAD

**Issue by mrozbarry** [doublespeakgames/adarkroom#470]
After playing for a while, I noticed I couldn't swap between my windows, and determined the bug happened when I found a downed aircraft.

This is what Chrome inspector is telling me:

![](http://i.imgur.com/upo8eCX.png)

`#spacePanel` completely overlaps most of the important UI, making this impossible to continue playing, aside from manually changing the css (which I have been doing).

**Comment by Continuities** [comment]
Whoa, that's weird. Just tried myself, and could not reproduce. Chrome
version? Plugins/extensions?

**Comment by mrozbarry** [comment]
Mac OSX Version 10.10.5 (14F1605)
Chrome Version 48.0.2564.109 (64-bit)
No extensions that do DOM manipulations.

**Comment by mrozbarry** [comment]
Just relaunched Chrome, empty cache + hard reload, and now things are working as expected.  Weird, this was a problem for me for quite a few hours, but it's possible that there was a Chrome update that got applied when I relaunched?
