### ISSUE TITLE
[spoilers inside] localization: unclear what you mean by charm

### ISSUE THREAD

**Issue by vankasteelj** [doublespeakgames/adarkroom#477]
## Don't read below if you don't want to be spoiled of some of the game's possibility!!!

Hi, I'm translating the game, and there's something that's a little unclear to me. When finding objects in traps (maybe when wandering), you sometimes get a "charm". That item can then be used later to give to a wanderer, for it to tell you the story of his attempt at space-conquest.

I'm wondering what "charm" is in this situation. I'm guessing it's a charm from bracelets the crew of the fleet were wearing (like in "Mary wears a bracelet with little charms on it every day."), or charms they had to tell what "rank" they are in the fleet.

But I might be missing something, and it could also be a charm, where magic is involved: "the sorcerer made a charm with a bone and some rare bird's feather".

It could also, I'm not sure why, be "The pharaons were given charms to protect them in the afterlife".

All these aren't translated the same in French. Hence this issue. Maybe you'd have a picture/drawing/description of what "charm" means in this RPG?

Thanks

**Comment by Continuities** [comment]
I'm gonna be super unhelpful and say that both interpretations of the word work =)

**Comment by groteworld** [comment]
@Continuities is typically 100% right as to interpretations (he made it, you know?)

I've always interpreted it as a lapel pin, badge typically worn over the heart, or a war medal of honor. The player doesn't know what it is though, they don't remember ever seeing one of these "charms". 

![image](https://cloud.githubusercontent.com/assets/1421810/14572354/6b000858-031c-11e6-9222-40b2842c795b.png)

**Comment by vankasteelj** [comment]
I get that, but it's impossible in French. The current translation is "Charme", which in french is either "this man is charming" or "a magic spell", but it cannot be an object. So when I saw that the wanderer took the charm and looked at it, I was all like wtf. 

In french, an object that would be a charm could be "amulette" (an amulet) or "breloque" (shiny metal thingy, a charm or a medal) or "fétiche" (for example, a vodo fetish, a doll, ...). 

But these terms cannot be changed from one to the other without huge changes in both the word and the meaning.

I'll stick with my first idea and take "breloque" then, which can be a "pins you pin on your chest", but also a "piece of jewelry you can put inside a bracelet or a necklace".

**Comment by Continuities** [comment]
Sounds to me like "breloque" is the right word.

**Comment by vankasteelj** [comment]
and in a magic universe, a breloque could be enchanted, like any other inanimate object (staff, rings, ...)

**Comment by AndySky21** [comment]
I will update Italian translation according to this.
Thanks for the note.
