### ISSUE TITLE
[spoilers inside] localization issue, need enlightenment

### ISSUE THREAD

**Issue by vankasteelj** [doublespeakgames/adarkroom#479]
Hi again,

I'm facing another localization issue with a word: `alien alloy`.

Is it alien as in "extratterrestrial" or as in "foreign"?

IMO it could be both, seeing what it's used for. But that would be the only mention of "extra-terrestrial" life then. Maybe more is in the work? 

Thanks

**Comment by AndySky21** [comment]
I could be wrong but...
- Spoiler below -
Are you sure this game is set on Earth?... maybe that alloy is not the
extraterrestrial thing in the game...
However the alloy is related to a spaceship, so it is properly "alien", not
only foreign.

**Comment by vankasteelj** [comment]
This game might be set on an earth-like planet, sure, there is no indication either way. We do know in the past space-travel tech existed, but that's about it. 

My issue is that in french, there is no word that holds both sense of "alien". It's either "extra-terrestrial", which would mean "a metal not from earth" (if the game is on earth, then it's metal from another planet; if the game is on an earth-like planet, then the metal could be from the planet we're currently in, or from another planet, but not earth anyway), either "from somewhere else" (that's what I meant by 'foreign').

**Comment by vankasteelj** [comment]
I've found a workaround, using "exotic", which has these meanings:
- "not from here (maybe from another part of this world)"
- "not from here (maybe from another planet)"
- "unknown"
- "exotic"
- "outlandish"
- "rare (very uncommon)"
- "mysterious"
