### ISSUE TITLE
Commented string translation

### ISSUE THREAD

**Issue by rjorel** [doublespeakgames/adarkroom#480]
Hi,
I discovered the game just the last week, and I remarked that some translations were not good (or just non-existent. So I cloned the repository to add translations (and fix some spelling mistake), and I saw commented strings like "A dusty Path"... for these strings, there are no lines like 
#: ../../script/events/encounters.js:396
above. Is it important ? I would like to propose corrections and new translations, but can I uncomment these strings to get a more comprehensive game ?

And just to finish, how can I make a pull request without forking the project (if it's possible) from my local repository ?

Raphael

**Comment by vankasteelj** [comment]
You need to translate the game using Pofiles, it's all in the wiki. Note that a [complete french translation](https://github.com/doublespeakgames/adarkroom/pull/478) is waiting to be merged, so it doesn't need to be done twice

**Comment by rjorel** [comment]
thanks, so I won't continue to complete french translation.
