### ISSUE TITLE
Maintainers inactive?

### ISSUE THREAD

**Issue by tehp** [doublespeakgames/adarkroom#494]
Hey @Continuities and @groteworld,

Are you guys planning on addressing any of the pull requests on the project?
I would like to make some contributions but I would like to know if you guys plan to pickup maintenance on ADR in the near future.

Thanks 😄

**Comment by Continuities** [comment]
Hey @tehp,

I wish I had the time. I occasionally have a few moments to close some of the smaller ones, but the bigger ones are unfortunately beyond my means at the moment. If only I didn't have this pesky day job...

**Comment by groteworld** [comment]
Plan to pick up again? Yes. I'll do my best to clean up some "skywalker" PRs here this weekend. Sometimes people like you just need to light the fire for us ;)

**Comment by Continuities** [comment]
Oh man, @groteworld is the best.

**Comment by tehp** [comment]
Oh awesome!
I was planning to start merging his PR's into my fork and then start fresh from there, but this is even better.

Thanks @groteworld
