### ISSUE TITLE
Better Path Item Quantities

### ISSUE THREAD

**Issue by cyreb7** [doublespeakgames/adarkroom#51]
Just finished playing (and loved it), but my one big annoyance is that when I return home after exploring the path, it would set the meat, bullets, etc to the amounts I had AFTER I was done exploring. This was very frustrating because by the end of the game, I had hundreds of bullets and cured meat at home and would be forced to click the up arrow at least fifty times after every exploration to replenish my 100 bullets and 40 cured meat.

The two solutions I would like is for the item amounts to be reset to the values set when you start along the path (provided you have enough of the item), and the other solution is to have a way to type an amount directly instead of needing to click the up arrow fifty times.

**Comment by cjhooker** [comment]
Just finished playing through and I'm interested in contributing. Took a look at the quantity-adjust buttons and thought they could benefit from being just a tad bigger to make targeting them easier. Like this:

BEFORE:
![image](https://cloud.githubusercontent.com/assets/11307282/7216737/e59e67d0-e5d6-11e4-8eb5-69f628e42f68.png)

AFTER:
![image](https://cloud.githubusercontent.com/assets/11307282/7216744/293e0a0e-e5d7-11e4-8293-c368251a3783.png)

Thoughts?

**Comment by skj3gg** [comment]
I like it! Please submit a PR!

**Comment by grotewold** [comment]
I believe this issue has been solved to the best of the projects abilities.

Thanks!
