### ISSUE TITLE
Gaining Resources whilst sitting in a dialog box

### ISSUE THREAD

**Issue by DennisFord98** [doublespeakgames/adarkroom#520]
Whilst I was reading through I dialog box I noticed that I was still gaining resources,this seemed to be somewhat game breaking that in a dialog where someone asks me for 500 wood I was able to just wait long enough for the wood to stack so I could give them some.

I cannot tell if this is an intentional part of the game or a bug.

**Comment by Continuities** [comment]
Not a bug. Blocking resource gain while a dialog is open could really stall
you, as dialogs can open without your knowledge.

**Comment by whit537** [comment]
This can be closed, I think.
