### ISSUE TITLE
your app for f-droid

### ISSUE THREAD

**Issue by theScrabi** [doublespeakgames/adarkroom#524]
Have you thought about putting your app on [fdorid](https://f-droid.org)?

**Comment by Continuities** [comment]
ADR-web isn't very mobile-friendly, unfortunately. The UI depends on
hover-state to convey information, and a lot of the game depends on
keyboard interaction.

**Comment by theScrabi** [comment]
Hm i see. I just hought so sice there is a version available on playstore.

**Comment by Continuities** [comment]
The mobile version has been heavily modified, and it's based on the web
source code at all.

**Comment by theScrabi** [comment]
ah alright.
