### ISSUE TITLE
travelTo Mechanics

### ISSUE THREAD

**Issue by jernaumorat** [doublespeakgames/adarkroom#53]
When `Engine.travelTo()` is called, instead of moving to the specified module, it increments the `panelIndex` to the supposed location of the module. In normal gameplay, this shouldn't be an issue, but I am writing a little bit of extra content (a new tab) and this suddenly becomes an issue. I will start trying to find a solution for this, but if anyone else has any suggestions or other input, I'd appreciate the help. I'm experienced in JS, but not so much with reading other people's syntax.

For the time being, I've worked around this with the `:nth-child` selector.

**Comment by chuglydude** [comment]
I will fix this send a new pull request

**Comment by gitupofftheflooranddosomework** [comment]
should be closed, this is no longer an issue
