### ISSUE TITLE
cramped forefinger

### ISSUE THREAD

**Issue by d-nnis** [doublespeakgames/adarkroom#533]
I've got a cramp in my right forefinger for buying 500+ scales to purchase one piece of alien alloy. (I wonder how that nomad could carry that much...)
How much to give for a fresh forefinger!?   :point_up_2:

Anyway, thx for the joy, going back to work now...  :rocket:

:trollface:

**Comment by VacuumSPP** [comment]
I think you should delete this as it's not an actual issue. Thanks for the laugh though!

**Comment by d-nnis** [comment]
Alrighty :-)

**Comment by d-nnis** [comment]
_I_ can close/ delete this issue!?

I don't seem to find any button that sais _delete_...

**Comment by VacuumSPP** [comment]
There should be a button for closing it next to the comment button.

Your issue raises a good suggestion though, multi-buy could be useful. You could add it to the 'Suggestions' section in the wiki or working on it yourself 👍

**Comment by d-nnis** [comment]
:-)
Found it!
