### ISSUE TITLE
Lithuanian translation not appearing in the list, not working

### ISSUE THREAD

**Issue by VacuumSPP** [doublespeakgames/adarkroom#543]
#540 I have recently completed and added a Lithuanian translation to the game, although it does not seem to appear in the language list in-game and once I select in from the main page or enter the URL manually, the game still appears in English.

First of all I realised I forgot the strings.js file, which I added in a separate pull request. #541 
Since that didn't seem to fix the problem, I saw the unnecessary strings.mo file in the folder, which I decided to delete (still waiting for the merge #542 ) although I doubt that will fix it.

Any ideas what the problem is?

**Comment by Continuities** [comment]
Probably because I haven't deployed a new build of ADR in a while! I'll get
around to it eventually, but life's busy.

**Comment by VacuumSPP** [comment]
Oh right I see! I was just wondering if there's anything wrong with it is all. Thank you for the quick reply! 👍
