### ISSUE TITLE
Weapons available for use

### ISSUE THREAD

**Issue by maciej-gurban** [doublespeakgames/adarkroom#550]
Just fought 3 fights inside a sulphur mine having one me: steel sword, bolas and rifle. During the first fight, only the first two weapons were available. During second and third fights, the rifle became available as well.

Is that intended behaviour?

**Comment by j-f1** [comment]
You probably found the rifle and some bullets after the first fight.

**Comment by gitupofftheflooranddosomework** [comment]
Close, cannot be replicated after multiple tests

**Comment by esaruoho** [comment]
@maciej-gurban any chance you could close this ticket, please?
