### ISSUE TITLE
[brainstorm] Road crew

### ISSUE THREAD

**Issue by chadwhitacre** [doublespeakgames/adarkroom#559]
What if you could send out a road crew? Lays road as it goes. Consumes water/meat at twice the normal rate while laying road, normal rate while traveling on road.

Because clearly this is the objectively wrong placement for the road to the iron mine:

![screen shot 2017-08-11 at 7 47 44 am](https://user-images.githubusercontent.com/134455/29211853-72d8b542-7e69-11e7-98f7-1b4ab21f03df.png)

**Comment by whit537** [comment]
😖 

![screen shot 2017-08-11 at 7 51 34 am](https://user-images.githubusercontent.com/134455/29211928-f19b42a0-7e69-11e7-92ae-606398d39416.png)

**Comment by whit537** [comment]
Another use case is when the ship is in a corner. It'd be nice to lay a road straight out to an edge without having to find/finish a suburb.

**Comment by gitupofftheflooranddosomework** [comment]
This would make the game a lot easier and shorter, i vote that this is closed

**Comment by chadwhitacre** [comment]
I'm fine to close, was a brainstorm, I'm not going to champion this.

**Comment by esaruoho** [comment]
@chadwhitacre could you close this ticket, thanks! :)

**Comment by chadwhitacre** [comment]
Sure thing! :)
