### ISSUE TITLE
Request: Put a villager on trap check, and wood gathering

### ISSUE THREAD

**Issue by keybounce** [doublespeakgames/adarkroom#564]
I'd like to automate the trap checking and wood gathering.

Even if it costs me one villager each, right now I can't really leave this tab.

And how did this tiny dark room become so addictive?

**Comment by keybounce** [comment]
EDIT: Especially if I'm going on the dusty trail, and come back to find that everyone has basically ignored the wood and traps for several hundred units worth.

**Comment by keybounce** [comment]
Ok, so apparently there is a "penalty" for being able to click the wood/traps button of being on a screen that triggers punitive events.

I don't like that design choice, but if it's intended that trying to move people allocations or do extra harvesting is painful, I can understand it not being automated.

**Comment by AndySky21** [comment]
You already have "wood gatherers", i.e. villagers who do not attend any other job. When you hit the "gather wood" button, you yourself go into the forest and gather branches. Do something for your community, lazy guy!
Traps are another story, they're the source for useful bargaining stuff, so it would be too easy if you had them automatically contributing to the economy of the village.
And don't think I wouldn't appreciate a "trap checker" job... but it's always an idle game, after all.

**Comment by gitupofftheflooranddosomework** [comment]
close, doesn't appear to be of any value

**Comment by groteworld** [comment]
Any value to whom?

**Comment by gitupofftheflooranddosomework** [comment]
Any value to the game, game functions or future of the game

**Comment by groteworld** [comment]
But in who’s eyes? That’s the thing about open source projects. Everyone
has an opinion on what could make the game better or add value to it. I
just must have missed the memo where you became the decider of value to
this project.

**Comment by gitupofftheflooranddosomework** [comment]
To start if you read the rest of the thread @AndySky21 also agreed that this would be nice however it would be too easy for the game to progress if you did such, its also worth noting that you have made any changes since 2016, i have an interest in continuing the devlopment of this and moving it forward, as you said it is open source and it is a group decision, however it appears as if the majority of said group has disappeared, including yourself.

**Comment by Continuities** [comment]
I appreciate your passion for the project @gitupofftheflooranddosomework, but please be aware of how your tone can affect other contributors. We're all volunteers here, and we're all on the same team.

That said, I agree with @AndySky21. Manually checking traps and gathering wood is intended as an early-game growth strategy before you have the resources to create automation through gatherers and hunters.

**Comment by gitupofftheflooranddosomework** [comment]
@Continuities I do not mean to be rude, I just wish to move this project forward and there isnt a need for this and should be closed.

**Comment by Continuities** [comment]
Thanks @gitupofftheflooranddosomework.

Agreed. I think this function is already covered by wood gatherers and hunters. Closing.
