### ISSUE TITLE
Just found "Slow metabolism" and "Desert rat" ...

### ISSUE THREAD

**Issue by keybounce** [doublespeakgames/adarkroom#576]
So other than reading the code, how in the heck do you expect anyone to trigger slow metabolism or desert rat?

**Comment by AndySky21** [comment]
You aren't. If you do not, it means you can survive with your basic consumption rates.
But maybe the message when dying from starvation/dehydration could hint to "something good" happening if you do it again and again. Just something like 
`"you must learn how to cope with that..."`

**Comment by esaruoho** [comment]
so, hold on - does this mean that the more i die in the desert, the more chances i'll get a slow metabolism and desert rat - do i understand that one is for hunger and the other for thirst?

**Comment by Continuities** [comment]
Correct. There perks exist for two reasons: To help players that might not
be as good at carefully planning their expeditions, and to account for the
possibility that random map generation *might* create a map where important
things are just out of reach. That's how lazy I am.

**Comment by gitupofftheflooranddosomework** [comment]
close, is not an issue but rather an explanation of how something works
