### ISSUE TITLE
Idea: Can I make a game guide?

### ISSUE THREAD

**Issue by Lyn0313** [doublespeakgames/adarkroom#606]
I felt a little uncomfortable because I had no explanation for playing games while playing games.
So I want to write a brief description of the game and let people see it in the game.

For example, people can move with mouse clicks at 'A Dusty Path', but they can also move with arrow keys. But I didn't know this. I'd like to write things like this.

**Comment by Continuities** [comment]
There are plenty of game guides available on the internet. Feel free to
write another. Part of the mystery of ADR is learning how to interact with
it, though, so there will never be an in-game guide.

**Comment by gitupofftheflooranddosomework** [comment]
Move to close in order to make resolving issues easier.
