### ISSUE TITLE
Copy-Pasting code into Google Docs makes ENTIRE SAVE FILE human-readable

### ISSUE THREAD

**Issue by unbeatablegamer** [doublespeakgames/adarkroom#621]
Basically I was messing around and wanted to transfer my progress from my laptop to my PC, so I decided to put the code in GDocs, also enabling data mining. When I did, this is what I found (the map has been edited so I might be able to get more resources. Also some of the white text has been made black for convenient viewing.):
[Click!](https://docs.google.com/document/d/17iiU20BCqavo17f3Hb_jp_UvR7RtTLf6zY2c4UUqGzQ/edit?usp=sharing)
All of this _**PRECISELY**_ matches my data from the time of the save.

**Comment by Continuities** [comment]
Neat! Not sure this is an issue, though. It's pretty easy to hack saved games, if you're so inclined.
