### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by muuvmuuv** [doublespeakgames/adarkroom#639]
Build for Mac and Windows? Browser is cool but an application looks nicer :)

**Comment by muuvmuuv** [comment]
Made a first sample here: https://github.com/muuvmuuv/electron-adarkroom

**Comment by JordMonte512** [comment]
Is this still around ?

**Comment by muuvmuuv** [comment]
Nope. It stopped working the last time I tried and no time for further development. But I suggest making it a PWA rather an electron app.
