### ISSUE TITLE
Spoiler on item description

### ISSUE THREAD

**Issue by dcormier** [doublespeakgames/adarkroom#649]
When equipping to embark, if you hover over `energy cell`, there's a spoiler for what it's used for, long before you actually have access to the thing that uses the `energy cell`. [Image showing spoiler.](https://user-images.githubusercontent.com/216265/53584342-64244880-3b51-11e9-8b03-241a76049f02.png)

**Comment by hudidit** [comment]
Wow, we have laser rifle in this game?!

**Comment by Jaredcscott** [comment]
I fixed this, I'll submit a PR.

**Comment by Jaredcscott** [comment]
This issue has been resolved with PR #660 and can be closed.
