### ISSUE TITLE
puzzled about the relationship between versions

### ISSUE THREAD

**Issue by simonwiles** [doublespeakgames/adarkroom#650]
What's the relationship between the mobile versions and the web version?  I completed the web version (and loved it, thanks so much!), and decided to buy the Android version, more as a thank-you than anything else.  Is there much more content in the Android version?  I like the interface *much* less on the mobile version -- it's much less fun to play -- but will continue if there's more story-line to be had, different challenges etc.  I'd much rather pay for expanded content on the browser-based version, though; is that ever likely to be an option?

Thanks!

**Comment by Continuities** [comment]
Thanks for supporting! The mobile version of ADR has modified timings, some
narrative additions, and a secret ending. I'd say it's less like additional
story-line, and more like a reimagining. Sorry you don't like the mobile
interface. Amir had a lot of challenges when adapting the original UI for
touch (so much of ADR's information is contained in hover-states, which
don't exist without a mouse), not to mention the drastically reduced
screen-size.

As for expanded content on the web, you're unlikely to see the mobile
content land there. I'm not really working on ADR any more, and so content
is added as the community adds it (when I get off my lazy ass and merge).
When there _is_ new content, it's different from mobile.

**Comment by simonwiles** [comment]
Thanks for the explanation.  I didn't mean to be too harsh on the Android UI -- I appreciate it's tougher in many ways (although there is plenty of low-hanging fruit that could improve it considerably).

Thanks again for a really lovely game :)
