### ISSUE TITLE
Mobile / desktop connect

### ISSUE THREAD

**Issue by JordMonte512** [doublespeakgames/adarkroom#674]
Hey. 

Is there possibility to create a shared game save between mobile and desktop, one that uses some sort of SSO to share saved progress between mobile and desktop?

Currently there is no way to import desktop exports to mobile, I am assuming this is down to 2 things:
1. Possible difference between the mobile and web versions
2. clipboard sizes due the the amount of information on the export

**Comment by Continuities** [comment]
They're just really different games. Resource costs and timings were
modified on the mobile version to support more active play than the web
version's idleness.

**Comment by JordMonte512** [comment]
Okay cool. 

No problem.

I will close the issue
