### ISSUE TITLE
Modifying Base64 save file to a high number breaks the game

### ISSUE THREAD

**Issue by WesleyBryie** [doublespeakgames/adarkroom#689]
Modifying the save be decoding it and encoding it by simply modifying the resource numbers breaks the game
![image](https://user-images.githubusercontent.com/93141203/153254841-bb743235-bf24-4980-b62e-e8b01ba04bcc.png)

**Comment by keventhen4** [comment]
This is a really late reply, but how so?

**Comment by WesleyBryie** [comment]
Having not have played this game since the issue creation, I could not tell you. I also do not know what values I changed in the save file. I will close this as invalid due to this.
