### ISSUE TITLE
Sounds for the game

### ISSUE THREAD

**Issue by groteworld** [doublespeakgames/adarkroom#78]
I've been thinking about this lately,

What is everyone's thoughts on sound effects for the game? Before I go as far as add sound functions, I want to get the community opinion.

**Comment by eazellou** [comment]
I'm sorry I haven't responded for so long.  Unfortunately I'm not going to be able to work on this project any longer.  I really think that the style of adarkroom really lends itself to silence, it fits with the retro text-based game feel for there to be no sound effects in my opinion.  

If you do decide that adding sound is the way to go, I hope you are able to find someone who shares the same vision for the game as you.  To send an email to all of the Performing Arts Technology majors at Michigan, just email cpat.majors@umich.edu.  There are a lot of talented people on that list, and maybe someone will be interested.

**Comment by AndySky21** [comment]
Hey there. Would you mind having sounds coming from an open source library?
I doubt I can record them on my own, but I found something online and I could take it for me if you are interested.
@Continuities, I know ADR is one long deafening moment of silence, but I like the original idea. Short sounds for commands (e.g. fire, traps, buildings), dungeon entrance, enemies appearance, maybe room/outside events, and possibly attacks.

**Comment by Continuities** [comment]
I'm not opposed to sound, so long as they're classy and optional.

**Comment by vankasteelj** [comment]
Here's a website grouping some sample and loops that could be used, http://www.universal-soundbank.com

**Comment by gitupofftheflooranddosomework** [comment]
Is this something that we want to do ?

**Comment by jorsi** [comment]
Hi all, late to the thread.

I've been working on implementing audio for the game at https://github.com/jorsi/adarkroom.

My plan is to have ambient background music for each area:

1. A Dark Room - ambience changes based on fire value
2. A Silent Forest - ambience changes based on number of huts (i.e. each title change)
3. A Dusty Path - one static song
4. World - one static song
5. Ship - one static song
6. Space - idea is to change backing music on each atmosphere change (possibly every other)
7. Ending
8. Each event, landmark, and encounter would have their own mini track. 
9. Sound effects for all main buttions: build, craft, buy, gather wood, check traps, embark, etc.

So far I've programmed the majority of code I'll need to play the audio. Next is working on the actual sounds. You can run my repo now and see all the audio working in the proper places, but the audio itself is definitely not what I imagine --all the audio is currently random sfx/loops that I used as placeholders.

I don't think it should take too much longer to do the sound design. Will update as I go!

**Comment by jorsi** [comment]
Trying to keep it lo-bit like Atari but with a modern twist. So far have rough ambience and sound effects up to and including the world screen.

Not sold on the village ambient tracks -- very much need to dial them back a lot. The room and path ambience I think is more what the overall vibe should be.

If anyone is still looking at this thread, would love to hear feedback.

**Comment by SimonDarksideJ** [comment]
I think this will be awesome if it can be pulled off. Just tricky within the current JS framework.

**Comment by jorsi** [comment]
I already have a js web audio version in. Needs some polish but it’s working fine enough now.

**Comment by jorsi** [comment]
@groteworld Any interest in this feature still? If not, would it be alright to if I could host a version of my own and call it A Dark and Quiet Room? :D

**Comment by ajslater** [comment]
jorsi this all pretty good. i think i agree about the village tracks and more ambient tracks.

**Comment by jorsi** [comment]
All sound effects and music implemented in the game now. Audio engine has been polished as well.

There are handful of musical themes I'm looking to improve: https://github.com/jorsi/adarkroom/issues.

If anyone wants to go through the game easily to see all the sounds, you can open up the browser console and type `Engine.enableGodMode()` to open up all areas, have all stores, and high health/water. You'll need to wait until after the builder is warm enough for it to work properly.

https://jorsi.github.io/adarkroom/

**Comment by ajslater** [comment]
A) The sounds are great and add a lot of charm to the game.

I haven't played all the way through yet, but.

B) The 'beeping' during "A Raucous Village" makes me hit the mute button. Should probably replace that one.

**Comment by jorsi** [comment]
Appreciate the feedback, the village themes have been some of the more difficult ambiences to get right. I'll take another shot at that one.

**Comment by Continuities** [comment]
Just wanted to chime in and say that this sounds really great! We might
want to consider stopping audio when the game isn't in focus so as not to
bother people while they're idling. Then again, changes in sound could
prompt people to tab back and look at the game. Thoughts?

**Comment by jorsi** [comment]
I think that would be reasonable. It would avoid people muting the tab and then wondering why there’s no audio when coming back to it as well.

**Comment by orsi** [comment]
Turns out there was a lingering error in Safari preventing audio playback. Fixed it and it should work in all browsers now.... hopefully :P

**Comment by esaruoho** [comment]
since sound now works as per @orsi 's work, can @groteworld  close the ticket, please?
